<!DOCTYPE html >
<html>
<head>
    <title><?=MetaHelper::getTitle(); ?></title>
    <!--Latest compiled and minified CSS-->
</head>
<body>
<a href="/">Home</a>
<a href="/index.php?route=book/index">Books</a>
<a href="/index.php?route=index/contact">Contact</a>
<a href="/index.php?route=security/login">Login</a>
<hr>
<div class="container">
<?=$content?>
</div>
<hr>
&copy; <?=date('Y-m-d H:i:s')?>
</body>
</html>